require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/MethodLength:
  Max: 15

RSpec/ExampleLength:
  Max: 20
